INSERT INTO project (project_name, project_description, github_url) VALUES
	("Edinburgh Remakery Inventory Management System", "This is the first project and its description.", "https://www.github.com/jackspyder/Remake"),
	("Mobile Car Game (WIP)", "This is the first project and its description.", "https://www.github.com/boxfort/car-game"),
	("Custom Forum", "This is the first project and its description.", "https://www.github.com/boxfort/Boxfort16mb"),
	("OpenGL Renderer", "This is the first project and its description.", "https://www.github.com/boxfort/OpenGLProject"),
	("Napier Bank Message Filtering Service", "This is the first project and its description.", "https://www.github.com/boxfort/nbmfs"),
	("Noogle", "This is the first project and its description.", "https://www.github.com/boxfort/SET08013-CW1"),
	("Travelling Salesman Problem", "This is the first project and its description.", "https://www.github.com/boxfort/TSP2Opt"),
	("Oscillator", "This is the first project and its description.", "https://www.github.com/boxfort/oscillator");


INSERT INTO project_image (project_id, img_path) VALUES
	(1, "remade1.png"),
	(1, "remade2.png"),
	(1, "remade3.png"),
	(1, "remade4.png"),
	(1, "remade5.png"),
	(2, "car1.png"),
	(2, "car2.png"),
	(2, "car3.png"),
	(2, "car4.png"),
	(2, "car5.png"),
	(3, "1.jpg"),
	(4, "opengl1.png"),
	(5, "NBMFS1.png"),
	(5, "NBMFS2.png"),
	(5, "NBMFS3.png"),
	(5, "NBMFS4.png"),
	(5, "NBMFS5.png"),
	(6, "noogle1.png"),
	(6, "noogle2.png"),
	(6, "noogle3.png"),
	(7, "2opt1.png"),
	(8, "ggj1.png"),
	(8, "ggj2.png"),
	(8, "ggj3.png"),
	(8, "ggj4.png");

INSERT INTO tech (tech_html) VALUES
	("<i class='devicon-html5-plain colored'></i> HTML"),
	("<i class='devicon-javascript-plain colored'></i> Javascript"),
	("<i class='devicon-php-plain colored'></i> PHP"),
	("<i class='devicon-css3-plain colored'></i> CSS"),
	("<i class='devicon-jquery-plain colored'></i> JQuery"),
	("<i class='devicon-laravel-plain colored'></i> Laravel"),
	("<i class='devicon-csharp-plain colored'></i> C#"),
	("<i class='devicon-dot-net-plain colored'></i> .net"),
	("<i class='devicon-mysql-plain colored'></i> MySQL"),
	("<i class='devicon-cplusplus-plain colored'></i> C++"),
	("<img src='img/unity.png' class='custom-icon'/> Unity"),
	("<img src='img/blender.png' class='custom-icon'/> Blender"),
	("<img src='img/opengl.png' class='custom-icon'/> OpenGL"),
	("<i class='devicon-java-plain colored'></i> Java");

INSERT INTO project_tech (project_id, tech_id) VALUES
	(1, 1),
	(1, 5),
	(1, 3),
	(1, 4),
	(1, 6),
	(1, 9),
	(2, 7),
	(2, 11),
	(2, 12),
	(3, 1),
	(3, 3),
	(3, 4),
	(3, 9),
	(4, 10),
	(4, 13),
	(5, 7),
	(5, 8),
	(6, 7),
	(6, 8),
	(7, 14),
	(8, 7),
	(8, 11);
